apiVersion: v1
kind: Pod
metadata:
  name: payment-processor
  labels:
    app: payment-processor
spec:
  containers:
    - name: payment-processor
      image: aliok/generic-service:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      env:
        - name: REPLY_TYPE
          value: "com.mycompany.paymentprocessed"
        - name: REPLY_PERCENTAGE
          value: "100"
        - name: SOURCE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: payment-processor
spec:
  selector:
    app: payment-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: payment-processor-trigger
spec:
  broker: default
  filter:
    attributes:
      type: com.mycompany.paymentreceived
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: payment-processor
